### ISSUE TITLE
pretrained_run_models() fails if XZ-file of a year outside the range doesn't exist

### ISSUE THREAD

**Issue by maartenschermer** [UtrechtUniversity/patent-breakthrough#72]
running: 
```
sim_spec = SimulationSpecification(
    year_start=1870,
    year_end=1910,
    window_size=11,
    window_shift=1,
)

pretrained_run_models(prep_bert, model_bert, sim_spec, patent_dir, output_fp, cpc_fp)
```
fails:
```
FileNotFoundError: [Errno 2] No such file or directory: 'patents/1860.xz'
```
I think because `SimulationSpecification.year_ranges()` returns ranges that stretch outside the specified window. 
Possibly related (but maybe by design?), depending on the specs, the year_ranges are sometimes wider than window_size. With the values from the example, the year_ranges function yielded ranges that were 21 elements long, the first one being:
```
[1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880]
```

**Comment by qubixes** [comment]
The fact that it won't start on the `year_start` year is by design. I do understand it's confusing though, so if there's a better solution I'm happy to hear it. The problem I was trying to solve is that I wanted to keep the window shift consistent with different values of year_start.  So that if you start from 1860, and then from 1861 with a window of let's say 11 and a shift of 5, then you would have 1860-1870, 1861-1871, 1865-1875, 1866-1876, etc.

It's weird that you get 21 year windows when you use a window_size of 11 though, I can't see how that would come about. I'll try to reproduce it.

**Comment by qubixes** [comment]
I found the issue. Indeed with a window_shift of 1, there shouldn't be any issue with what I described. I guess for reusability there might still be the issue that the START_YEAR parameter might be different, i.e. it shouldn't be hard coded..
